### ISSUE TITLE
Documentation of Missing Text/Links on QualityNode Website

### ISSUE THREAD

**Issue by xadistic** [SwiftSwamp/QualityNode#2]
Listed are the text errors or missing links on the website.

https://docs.google.com/document/d/1sipVAqM3UDrHFpWdTWBz9Pd3f0UiYblLs-D5p7tyZxA

**Comment by SwiftSwamp** [comment]
Issues with QualityNode at the moment will be slow due to GlacialRealms and other projects but thanks for the submission!!

**Comment by SwiftSwamp** [comment]
Thank you! I've opened a new issue regarding the refining of QualityNode's information / text.
